// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cache} from '../models';
import {models} from '../models';
import {main} from '../models';
import {search} from '../models';

export function AnalyzeProcedure(arg1:string,arg2:string,arg3:string,arg4:string):Promise<cache.StoredProcedureInfo>;

export function ClearAllTabs():Promise<void>;

export function CreateConnection(arg1:models.ConnectionPostModel):Promise<cache.Connection>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteTab(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:string):Promise<cache.TableDataResponse>;

export function GetConnection(arg1:string):Promise<cache.Connection>;

export function GetConnections(arg1:boolean):Promise<Array<cache.ConnectionDetail>>;

export function GetDatabases(arg1:string,arg2:boolean):Promise<Array<string>>;

export function GetSchema(arg1:string,arg2:string,arg3:boolean):Promise<cache.SchemaResponse>;

export function GetTableData(arg1:main.GetTableDataRequest):Promise<cache.TableDataResponse>;

export function GetTableDataCount(arg1:main.GetTableDataCountRequest):Promise<number>;

export function GetViewData(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<cache.TableDataResponse>;

export function LoadTabs():Promise<Array<cache.Tab>>;

export function SaveTab(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:string):Promise<Array<search.SearchResult>>;

export function TestConnection(arg1:cache.Connection):Promise<void>;

export function UpdateConnection(arg1:string,arg2:models.ConnectionPostModel):Promise<cache.Connection>;

export function UpdateConnectionSettings(arg1:string,arg2:string,arg3:boolean):Promise<void>;
