// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cache} from '../models';
import {main} from '../models';
import {search} from '../models';

export function AnalyzeProcedure(arg1:string,arg2:string,arg3:string,arg4:string):Promise<cache.StoredProcedureInfo>;

export function CreateConnection(arg1:cache.Connection):Promise<cache.Connection>;

export function DeleteConnection(arg1:string):Promise<void>;

export function GetBackgroundLoaderStatus(arg1:string,arg2:string):Promise<cache.BackgroundLoaderStatusResponse>;

export function GetConnection(arg1:string):Promise<cache.Connection>;

export function GetConnections():Promise<Array<cache.Connection>>;

export function GetDatabases(arg1:string,arg2:boolean):Promise<Array<string>>;

export function GetLoadingStates(arg1:string,arg2:string):Promise<cache.LoadingStatesResponse>;

export function GetSchema(arg1:string,arg2:string,arg3:boolean):Promise<cache.SchemaResponse>;

export function GetTableData(arg1:main.GetTableDataRequest):Promise<cache.TableDataResponse>;

export function GetViewData(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<cache.TableDataResponse>;

export function ProcedureSearch(arg1:string):Promise<Array<search.ProcedureSearchResult>>;

export function Search(arg1:string,arg2:string,arg3:string):Promise<Array<search.SearchResult>>;

export function StartBackgroundLoader(arg1:string,arg2:string):Promise<void>;

export function StopBackgroundLoader(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:cache.Connection):Promise<void>;

export function UpdateConnection(arg1:string,arg2:Record<string, any>):Promise<cache.Connection>;
